contact_links:
  - name: ğŸ“£ ì¼ë°˜ ë¬¸ì˜ëŠ” Discussionsì—ì„œ
    url: https://github.com/LeeKwang-min/kooks/discussions
    about: ì§ˆë¬¸ì´ë‚˜ ì¼ë°˜ì ì¸ ë…¼ì˜ëŠ” Discussions íƒ­ì„ ì´ìš©í•´ì£¼ì„¸ìš”.
