blank_issues_enabled: false # ë¹ˆ ì´ìŠˆ ì‘ì„± ë¹„í™œì„±í™”

template_chooser:
  - name: ğŸ› ë²„ê·¸ ë¦¬í¬íŠ¸
    description: ë²„ê·¸ë¥¼ ë°œê²¬í•˜ì…¨ë‚˜ìš”? ì•Œë ¤ì£¼ì„¸ìš”!
    template: bug_report.yml
  - name: âœ¨ ìƒˆë¡œìš´ ê¸°ëŠ¥ ì œì•ˆ
    description: í”„ë¡œì íŠ¸ì— ì¶”ê°€ë˜ì—ˆìœ¼ë©´ í•˜ëŠ” ê¸°ëŠ¥ì„ ì œì•ˆí•©ë‹ˆë‹¤.
    template: feature_request.yml
  - name: ğŸ”„ ë¦¬íŒ©í† ë§ ì œì•ˆ
    description: ì½”ë“œ ê°œì„ ì„ ìœ„í•œ ì œì•ˆì„ í•´ì£¼ì„¸ìš”.
    template: refactor_proposal.yml
  - name: â“ ì§ˆë¬¸
    description: í”„ë¡œì íŠ¸ì— ëŒ€í•´ ê¶ê¸ˆí•œ ì ì´ ìˆìœ¼ì‹ ê°€ìš”?
    template: question.yml

contact_links:
  - name: ğŸ“£ ì¼ë°˜ ë¬¸ì˜ëŠ” Discussionsì—ì„œ
    url: https://github.com/LeeKwang-min/kooks/discussions
    about: ì§ˆë¬¸ì´ë‚˜ ì¼ë°˜ì ì¸ ë…¼ì˜ëŠ” Discussions íƒ­ì„ ì´ìš©í•´ì£¼ì„¸ìš”.
